import Foundation

/// A `Cargo.lock`, which is what makes a resolved graph reproducible and, on a
/// phone, rebuildable with the network off.
struct CargoLockfile: Sendable, Equatable {
    struct Entry: Sendable, Equatable, Comparable {
        let name: String
        let version: SemanticVersion
        let checksum: String?
        /// `name version` strings, exactly as Cargo writes them.
        let dependencies: [String]

        static func < (lhs: Entry, rhs: Entry) -> Bool {
            lhs.name == rhs.name ? lhs.version < rhs.version : lhs.name < rhs.name
        }
    }

    /// Cargo's current lockfile format.
    static let formatVersion = 4
    static let registrySource = "registry+https://github.com/rust-lang/crates.io-index"

    let entries: [Entry]

    init(entries: [Entry]) {
        self.entries = entries.sorted()
    }

    init(graph: ResolvedGraph, rootName: String, rootVersion: String) {
        var entries: [Entry] = graph.packages.values.map { package in
            Entry(
                name: package.name,
                version: package.version,
                checksum: package.checksum,
                dependencies: package.dependencies.values
                    .map { "\($0.name) \($0.version)" }
                    .sorted()
            )
        }
        entries.append(
            Entry(
                name: rootName,
                version: SemanticVersion(rootVersion) ?? SemanticVersion(major: 0, minor: 0, patch: 0),
                checksum: nil,
                dependencies: graph.rootDependencies.values
                    .map { "\($0.name) \($0.version)" }
                    .sorted()
            )
        )
        self.init(entries: entries)
    }

    /// Cargo writes this header, and reproducing it keeps the file readable by
    /// desktop Cargo after a project leaves Crabrix.
    func render() -> String {
        var lines = [
            "# This file is automatically @generated by Cargo.",
            "# It is not intended for manual editing.",
            "version = \(Self.formatVersion)",
        ]
        for entry in entries {
            lines.append("")
            lines.append("[[package]]")
            lines.append("name = \"\(entry.name)\"")
            lines.append("version = \"\(entry.version)\"")
            if entry.checksum != nil {
                lines.append("source = \"\(Self.registrySource)\"")
                lines.append("checksum = \"\(entry.checksum ?? "")\"")
            }
            if !entry.dependencies.isEmpty {
                lines.append("dependencies = [")
                for dependency in entry.dependencies {
                    lines.append(" \"\(dependency)\",")
                }
                lines.append("]")
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    static func parse(_ source: String) -> CargoLockfile? {
        guard let document = try? TOMLParser.parse(source) else { return nil }
        guard let packages = document["package"]?.arrayValue else {
            return CargoLockfile(entries: [])
        }
        var entries: [Entry] = []
        for package in packages {
            guard let table = package.tableValue,
                  let name = table["name"]?.stringValue,
                  let versionText = table["version"]?.stringValue,
                  let version = SemanticVersion(versionText)
            else {
                continue
            }
            entries.append(
                Entry(
                    name: name,
                    version: version,
                    checksum: table["checksum"]?.stringValue,
                    dependencies: table["dependencies"]?.stringArrayValue ?? []
                )
            )
        }
        return CargoLockfile(entries: entries)
    }

    /// The pinned version of a crate, if this lockfile has one.
    func pin(for name: String) -> Entry? {
        entries.first { $0.name == name && $0.checksum != nil }
    }
}
