import Foundation

/// Projects that exercise real Rust algorithms and render their bounded result
/// in the native Output canvas. The source stays ordinary std-only Rust and is
/// fully editable; `README.md` turns each entry into a guided challenge.
enum RustVisualShowcaseCatalog {
    private static func project(
        id: String,
        title: String,
        detail: String,
        difficulty: RustShowcaseDifficulty,
        concepts: [String],
        challenge: String,
        source: String
    ) -> RustShowcaseProject {
        RustShowcaseProject(
            id: id,
            title: title,
            detail: detail,
            systemImage: "paintpalette.fill",
            category: .graphics,
            difficulty: difficulty,
            concepts: concepts,
            project: CrabrixProject(
                name: id,
                files: [
                    "Cargo.toml": RustShowcaseCatalog.manifest(
                        name: id
                    ),
                    "README.md": """
                    # \(title)

                    Run the project and open **Output** to see a native Rust Canvas.

                    ## Concepts
                    \(concepts.map { "- `\($0)`" }.joined(separator: "\n"))

                    ## Challenge
                    \(challenge)

                    ## Proof
                    The result is generated by the bundled compiler and rendered
                    only after Crabrix validates every dimension, palette color,
                    and pixel index.
                    """,
                    "src/main.rs": source,
                ],
                entryFile: "src/main.rs",
                provenance: nil,
                projectDescription: detail,
                tags: concepts,
                folder: "Visual Gallery",
                kind: .visual
            )
        )
    }

    static let projects: [RustShowcaseProject] = [
        project(
            id: "pixel-sunset",
            title: "Pixel Sunset",
            detail: "Generate a layered sky, sun, and sea reflection",
            difficulty: .starter,
            concepts: ["loops", "coordinates", "palette"],
            challenge: "Move the sun, widen its reflection, or design a new palette.",
            source: """
            const HEX: &[u8] = b"0123456789abcdef";

            fn main() {
                let width: usize = 24;
                let height: usize = 16;
                let mut pixels = String::new();

                for y in 0..height {
                    for x in 0..width {
                        let dx = x as i32 - 17;
                        let dy = y as i32 - 6;
                        let sun = dx * dx + dy * dy <= 9;
                        let color = if sun {
                            4
                        } else if y < 5 {
                            1
                        } else if y < 9 {
                            2
                        } else if x.abs_diff(17) < 3 {
                            4
                        } else if (x + y) % 4 == 0 {
                            5
                        } else {
                            3
                        };
                        pixels.push(HEX[color] as char);
                    }
                }

                println!(
                    r##"CRABRIX_CANVAS:{{"title":"Pixel Sunset","width":24,"height":16,"palette":["#111827","#312E81","#F97316","#0F766E","#FDE68A","#22D3EE"],"pixels":"{}"}}"##,
                    pixels
                );
                println!("Edit the coordinates, then Run again.");
            }
            """
        ),
        project(
            id: "cellular-garden",
            title: "Cellular Garden",
            detail: "Evolve a tiny cellular automaton into a living pattern",
            difficulty: .intermediate,
            concepts: ["grids", "neighbors", "simulation"],
            challenge: "Run three generations or invent a different birth rule.",
            source: """
            const W: usize = 24;
            const H: usize = 16;

            fn neighbors(grid: &[bool], x: usize, y: usize) -> u8 {
                let mut total = 0;
                for dy in [-1_i32, 0, 1] {
                    for dx in [-1_i32, 0, 1] {
                        if dx == 0 && dy == 0 { continue; }
                        let nx = x as i32 + dx;
                        let ny = y as i32 + dy;
                        if nx >= 0 && ny >= 0
                            && nx < W as i32 && ny < H as i32
                            && grid[ny as usize * W + nx as usize]
                        {
                            total += 1;
                        }
                    }
                }
                total
            }

            fn main() {
                let mut grid = vec![false; W * H];
                for (x, y) in [
                    (4, 5), (5, 6), (3, 7), (4, 7), (5, 7),
                    (14, 4), (15, 4), (16, 4), (16, 5),
                ] {
                    grid[y * W + x] = true;
                }

                let mut next = vec![false; W * H];
                for y in 0..H {
                    for x in 0..W {
                        let count = neighbors(&grid, x, y);
                        next[y * W + x] = count == 3
                            || (grid[y * W + x] && count == 2);
                    }
                }
                let pixels: String = next.iter()
                    .map(|alive| if *alive { '2' } else { '0' })
                    .collect();
                println!(
                    r##"CRABRIX_CANVAS:{{"title":"Cellular Garden","width":24,"height":16,"palette":["#071A13","#166534","#4ADE80"],"pixels":"{}"}}"##,
                    pixels
                );
                println!("One generation evolved locally.");
            }
            """
        ),
        project(
            id: "mandelbrot-canvas",
            title: "Mandelbrot Canvas",
            detail: "Turn complex-number iteration into a fractal image",
            difficulty: .advanced,
            concepts: ["floats", "iteration", "fractals"],
            challenge: "Zoom into a new center or increase the iteration limit.",
            source: """
            const HEX: &[u8] = b"0123456789abcdef";

            fn main() {
                let width = 32;
                let height = 20;
                let mut pixels = String::new();

                for py in 0..height {
                    for px in 0..width {
                        let cx = px as f64 / width as f64 * 3.2 - 2.2;
                        let cy = py as f64 / height as f64 * 2.2 - 1.1;
                        let (mut x, mut y, mut step) = (0.0, 0.0, 0);
                        while x * x + y * y <= 4.0 && step < 30 {
                            let next_x = x * x - y * y + cx;
                            y = 2.0 * x * y + cy;
                            x = next_x;
                            step += 1;
                        }
                        let color = if step == 30 { 0 } else {
                            1 + step * 5 / 30
                        };
                        pixels.push(HEX[color] as char);
                    }
                }
                println!(
                    r##"CRABRIX_CANVAS:{{"title":"Mandelbrot Canvas","width":32,"height":20,"palette":["#020617","#1E1B4B","#4338CA","#7C3AED","#EC4899","#FDE047"],"pixels":"{}"}}"##,
                    pixels
                );
                println!("640 points iterated with real Rust.");
            }
            """
        ),
        project(
            id: "constellation-map",
            title: "Constellation Map",
            detail: "Plot stars and brightness on a midnight canvas",
            difficulty: .starter,
            concepts: ["tuples", "distance", "drawing"],
            challenge: "Add a constellation and connect it with a simple line rule.",
            source: """
            const W: usize = 24;
            const H: usize = 16;

            fn main() {
                let stars = [
                    (3, 4, 2), (8, 2, 1), (11, 7, 2),
                    (15, 5, 1), (19, 3, 2), (20, 11, 1),
                    (6, 12, 2), (13, 13, 1),
                ];
                let mut pixels = vec!['0'; W * H];
                for (x, y, brightness) in stars {
                    pixels[y * W + x] = if brightness == 2 {
                        '3'
                    } else {
                        '2'
                    };
                    if x + 1 < W { pixels[y * W + x + 1] = '1'; }
                }
                let pixels: String = pixels.into_iter().collect();
                println!(
                    r##"CRABRIX_CANVAS:{{"title":"Constellation Map","width":24,"height":16,"palette":["#020617","#334155","#93C5FD","#FFFFFF"],"pixels":"{}"}}"##,
                    pixels
                );
                println!("Eight stars plotted from tuple data.");
            }
            """
        ),
        project(
            id: "terrain-map",
            title: "Terrain Map",
            detail: "Generate islands from deterministic coordinate noise",
            difficulty: .intermediate,
            concepts: ["hashing", "thresholds", "maps"],
            challenge: "Change the seed and thresholds to create a new world.",
            source: """
            const HEX: &[u8] = b"0123456789abcdef";

            fn noise(x: u32, y: u32) -> u32 {
                let mut value = x.wrapping_mul(374_761_393)
                    ^ y.wrapping_mul(668_265_263);
                value = (value ^ (value >> 13))
                    .wrapping_mul(1_274_126_177);
                value ^ (value >> 16)
            }

            fn main() {
                let (width, height) = (24, 16);
                let mut pixels = String::new();
                for y in 0..height {
                    for x in 0..width {
                        let edge = x.min(width - 1 - x)
                            .min(y.min(height - 1 - y));
                        let value = noise(x, y) % 100 + edge * 8;
                        let color = match value {
                            0..=38 => 0,
                            39..=56 => 1,
                            57..=82 => 2,
                            83..=112 => 3,
                            _ => 4,
                        };
                        pixels.push(HEX[color] as char);
                    }
                }
                println!(
                    r##"CRABRIX_CANVAS:{{"title":"Terrain Map","width":24,"height":16,"palette":["#082F49","#0EA5E9","#FDE68A","#22C55E","#F8FAFC"],"pixels":"{}"}}"##,
                    pixels
                );
                println!("The same seed always rebuilds this island.");
            }
            """
        ),
        project(
            id: "color-waves",
            title: "Color Waves",
            detail: "Combine sine waves into an animated-looking still",
            difficulty: .intermediate,
            concepts: ["trigonometry", "sampling", "color"],
            challenge: "Change the frequencies or phase and compare the canvas.",
            source: """
            const HEX: &[u8] = b"0123456789abcdef";

            fn main() {
                let (width, height) = (32, 16);
                let mut pixels = String::new();
                for y in 0..height {
                    for x in 0..width {
                        let wave = ((x as f64 * 0.45).sin()
                            + (y as f64 * 0.70).cos()
                            + ((x + y) as f64 * 0.18).sin())
                            / 3.0;
                        let color = ((wave + 1.0) * 2.5)
                            .round() as usize;
                        pixels.push(HEX[color.min(5)] as char);
                    }
                }
                println!(
                    r##"CRABRIX_CANVAS:{{"title":"Color Waves","width":32,"height":16,"palette":["#172554","#1D4ED8","#06B6D4","#34D399","#FACC15","#FB7185"],"pixels":"{}"}}"##,
                    pixels
                );
                println!("Three waves sampled into 512 pixels.");
            }
            """
        ),
    ]
}
