import XCTest
@testable import Crabrix

final class SparseRegistryIndexTests: XCTestCase {
    func testIndexPathsFollowTheCratesIOLayout() {
        XCTAssertEqual(SparseRegistryIndex.indexPath(for: "a"), "1/a")
        XCTAssertEqual(SparseRegistryIndex.indexPath(for: "ab"), "2/ab")
        XCTAssertEqual(SparseRegistryIndex.indexPath(for: "abc"), "3/a/abc")
        XCTAssertEqual(SparseRegistryIndex.indexPath(for: "serde"), "se/rd/serde")
        XCTAssertEqual(SparseRegistryIndex.indexPath(for: "Serde_JSON"), "se/rd/serde_json")
        XCTAssertEqual(SparseRegistryIndex.indexPath(for: "cfg-if"), "cf/g-/cfg-if")
    }

    func testRejectsCrateNamesThatCouldEscapeTheIndexLayout() {
        for name in ["", "../etc", "with space", "sla/sh", ".hidden", String(repeating: "x", count: 65)] {
            XCTAssertNil(SparseRegistryIndex.indexPath(for: name), "\(name) must be rejected")
        }
    }

    func testParsesNewlineDelimitedIndexEntries() throws {
        let payload = """
        {"name":"demo","vers":"0.9.0","deps":[],"cksum":"\(String(repeating: "0", count: 64))","features":{},"yanked":true}
        {"name":"demo","vers":"1.0.0","deps":[{"name":"leaf","req":"^1","features":["x"],"optional":true,"default_features":false,"target":"cfg(unix)","kind":"normal","package":"leaf-real"}],"cksum":"\(String(repeating: "b", count: 64))","features":{"default":["std"]},"features2":{"extra":["dep:leaf"]},"yanked":false,"rust_version":"1.70","links":"z"}
        """
        let file = try SparseRegistryIndex.parse(Data(payload.utf8), name: "demo")

        XCTAssertEqual(file.versions.map(\.description), ["0.9.0", "1.0.0"])
        XCTAssertEqual(file.selectableVersions().map(\.description), ["1.0.0"])

        let latest = try XCTUnwrap(file.entry(for: SemanticVersion("1.0.0")!))
        XCTAssertTrue(latest.hasWellFormedChecksum)
        XCTAssertEqual(latest.rustVersion, "1.70")
        XCTAssertEqual(latest.links, "z")
        // features2 is merged into features, which is where `dep:` syntax lives.
        XCTAssertEqual(latest.features["extra"], ["dep:leaf"])

        let dependency = try XCTUnwrap(latest.dependencies.first)
        XCTAssertEqual(dependency.alias, "leaf")
        XCTAssertEqual(dependency.packageName, "leaf-real")
        XCTAssertTrue(dependency.isOptional)
        XCTAssertFalse(dependency.usesDefaultFeatures)
        XCTAssertFalse(dependency.applies(to: .wasm32WasiP1))
    }

    func testRejectsAnEmptyOrUnreadableIndexFile() {
        XCTAssertThrowsError(try SparseRegistryIndex.parse(Data(), name: "demo"))
        XCTAssertThrowsError(try SparseRegistryIndex.parse(Data("not json".utf8), name: "demo"))
    }
}

final class CargoLockfileTests: XCTestCase {
    func testRendersAndParsesBackTheSameGraph() throws {
        let lockfile = CargoLockfile(entries: [
            .init(
                name: "demo",
                version: SemanticVersion("0.1.0")!,
                checksum: nil,
                dependencies: ["anyhow 1.0.104"]
            ),
            .init(
                name: "anyhow",
                version: SemanticVersion("1.0.104")!,
                checksum: String(repeating: "c", count: 64),
                dependencies: []
            ),
        ])

        let rendered = lockfile.render()
        XCTAssertTrue(rendered.contains("version = 4"))
        XCTAssertTrue(rendered.contains("[[package]]"))
        XCTAssertTrue(rendered.contains(CargoLockfile.registrySource))

        let parsed = try XCTUnwrap(CargoLockfile.parse(rendered))
        XCTAssertEqual(parsed, lockfile)
        XCTAssertEqual(parsed.pin(for: "anyhow")?.version.description, "1.0.104")
        // The root package has no checksum and is therefore not a registry pin.
        XCTAssertNil(parsed.pin(for: "demo"))
    }

    func testParsesALockfileWrittenByDesktopCargo() throws {
        let parsed = try XCTUnwrap(CargoLockfile.parse("""
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 4

        [[package]]
        name = "itoa"
        version = "1.0.11"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "49f1f14873335454500d59611f1cf4a4b0f786f9ac11f4312a78e4cf2566695b"
        """))

        XCTAssertEqual(parsed.entries.count, 1)
        XCTAssertEqual(parsed.entries[0].name, "itoa")
    }

    func testRejectsUnsupportedRegistrySourceAndMalformedChecksum() {
        XCTAssertThrowsError(try CargoLockfile.parseValidated("""
        version = 4

        [[package]]
        name = "forked"
        version = "1.0.0"
        source = "git+https://example.com/forked"
        """)) { error in
            XCTAssertEqual(
                error as? CargoLockfileError,
                .sourceMismatch(package: "forked 1.0.0")
            )
        }

        XCTAssertThrowsError(try CargoLockfile.parseValidated("""
        version = 4

        [[package]]
        name = "broken"
        version = "1.0.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "short"
        """))
    }
}

final class CargoFingerprintTests: XCTestCase {
    private func fingerprint(
        version: String = "1.0.0",
        checksum: String = "abc",
        edition: String = "2021",
        features: [String] = ["default"],
        libraryPath: String = "src/lib.rs",
        dependencies: [CargoExtern] = []
    ) -> String {
        CargoFingerprint.compute(
            toolchainID: "artifacts-test-7",
            toolchainArtifactHash: "toolchain-hash",
            toolchainSemanticVersion: "1.96.0-dev",
            compilerFlags: CargoFingerprint.dependencyCompilerFlags,
            targetTriple: "wasm32-wasip1",
            resolverVersion: .v3,
            packageSource: CargoLockfile.registrySource,
            package: PackageID(name: "demo", version: SemanticVersion(version)!),
            checksum: checksum,
            crateName: "demo",
            edition: edition,
            features: features,
            libraryPath: libraryPath,
            dependencies: dependencies
        )
    }

    func testIsStableAcrossFeatureOrdering() {
        XCTAssertEqual(
            fingerprint(features: ["std", "alloc"]),
            fingerprint(features: ["alloc", "std"])
        )
        XCTAssertEqual(fingerprint().count, 16)
    }

    func testChangesWithEveryInputThatChangesTheArtifact() {
        let base = fingerprint()
        XCTAssertNotEqual(base, fingerprint(version: "1.0.1"))
        XCTAssertNotEqual(base, fingerprint(checksum: "def"))
        XCTAssertNotEqual(base, fingerprint(edition: "2018"))
        XCTAssertNotEqual(base, fingerprint(features: ["default", "std"]))
        XCTAssertNotEqual(base, fingerprint(libraryPath: "src/other.rs"))
        // A rebuilt dependency has to invalidate everything that links it.
        XCTAssertNotEqual(
            base,
            fingerprint(dependencies: [
                CargoExtern(alias: "dep", crateName: "dep", fingerprint: "0123456789abcdef"),
            ])
        )
    }

    func testChangesWhenDependencyAliasChanges() {
        let dependency = CargoExtern(
            alias: "foo",
            crateName: "bar",
            fingerprint: "0123456789abcdef"
        )
        let renamed = CargoExtern(
            alias: "bar",
            crateName: "bar",
            fingerprint: "0123456789abcdef"
        )
        XCTAssertNotEqual(
            fingerprint(dependencies: [dependency]),
            fingerprint(dependencies: [renamed])
        )
    }

    func testExternFileNamesMatchTheArtifactLayout() {
        let value = CargoExtern(alias: "serde", crateName: "serde", fingerprint: "0123456789abcdef")
        XCTAssertEqual(value.fileName(emit: .link), "libserde-0123456789abcdef.rlib")
        XCTAssertEqual(value.fileName(emit: .metadata), "libserde-0123456789abcdef.rmeta")
    }
}

final class CrateCompatibilityLedgerTests: XCTestCase {
    private func makeLedger() -> (CrateCompatibilityLedger, URL) {
        let url = FileManager.default.temporaryDirectory
            .appending(path: "ledger-\(UUID().uuidString).json")
        return (CrateCompatibilityLedger(storageURL: url), url)
    }

    func testRemembersBuildOutcomesAcrossInstances() throws {
        let (ledger, url) = makeLedger()
        defer { try? FileManager.default.removeItem(at: url) }
        let package = PackageID(name: "ryu", version: SemanticVersion("1.0.23")!)

        XCTAssertNil(ledger.outcome(forFingerprint: "aaaa"))
        ledger.record(package: package, fingerprint: "aaaa", outcome: .failed("umulhi is unimplemented"))
        XCTAssertEqual(ledger.outcome(forFingerprint: "aaaa"), .failed("umulhi is unimplemented"))

        // A fresh instance reads the same knowledge back off disk.
        let reopened = CrateCompatibilityLedger(storageURL: url)
        XCTAssertEqual(reopened.outcome(forFingerprint: "aaaa"), .failed("umulhi is unimplemented"))

        reopened.record(package: package, fingerprint: "aaaa", outcome: .built)
        XCTAssertEqual(reopened.outcome(forFingerprint: "aaaa"), .built)
    }

    func testIgnoresRecordsFromAnotherToolchain() throws {
        let (ledger, url) = makeLedger()
        defer { try? FileManager.default.removeItem(at: url) }
        ledger.record(
            package: PackageID(name: "old", version: SemanticVersion("1.0.0")!),
            fingerprint: "bbbb",
            outcome: .built,
            toolchain: "some-older-toolchain"
        )

        let reopened = CrateCompatibilityLedger(storageURL: url)
        XCTAssertNil(reopened.outcome(forFingerprint: "bbbb"))
    }

    func testRemoveAllClearsStoredKnowledge() {
        let (ledger, url) = makeLedger()
        defer { try? FileManager.default.removeItem(at: url) }
        ledger.record(
            package: PackageID(name: "x", version: SemanticVersion("1.0.0")!),
            fingerprint: "cccc",
            outcome: .built
        )
        ledger.removeAll()
        XCTAssertNil(ledger.outcome(forFingerprint: "cccc"))
    }
}
